In [47]:
# Задание 1
# # Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
import numpy as np

In [43]:
N = int(input ('Введите N: '))
a = np.arange(N-1, -1, -1)
print('Получите массив: ', a)


Введите N: 5
Получите массив:  [4 3 2 1 0]


In [ ]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
N = int(input ('Введите N: '))
a = np.diag(np.arange(N-1, -1, -1))
print(a)
print('Сумма элементов матрицы: ',a.diagonal().sum())

Введите N: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Сумма элементов матрицы:  10


In [50]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array([4, 12, -3])
from numpy import linalg
linalg.solve(a,b)


array([ 0.46666667,  3.84444444, -5.55555556])

In [51]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [61]:
# Задача 4 домашнего задания
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
#Остальные столбцы - количество покупок категорий товаров этим пользователем:

import matplotlib.pyplot as plt
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

proximity = []

def cosine (a,b):
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

for user in users_stats:
    proximity.append(round(cosine(user, next_user_stats),2))
print('Новый пользователь больше всего смахивает на покупателя № ',proximity.index(max(proximity))+1)

Новый пользователь больше всего смахивает на покупателя №  8
